export const LOAD_ARTICLE_DETAILS_DATA = 'LOAD_ARTICLE_DETAILS_DATA';
export const LOAD_ALL_ARTICLES_DATA = 'LOAD_ALL_ARTICLES_DATA';
export const SELECT_LANGUAGE_PREFERENCE = 'SELECT_LANGUAGE_PREFERENCE';