export const ERROR_LOAD_DATA = 'ERROR_LOAD_DATA';
export const LOAD_ARTICLE_DETAILS_DATA = 'LOAD_ARTICLE_DETAILS_DATA';
export const LOADING_DATA = 'LOADING_DATA';
export const RESET_ERROR = 'RESET_ERROR';

export const LOAD_ALL_ARTICLES_DATA = 'LOAD_ALL_ARTICLES_DATA';
export const ERROR_LOAD_ALL_ARTICLES_DATA = 'ERROR_LOAD_ALL_ARTICLES_DATA';
export const SELECT_LANGUAGE_PREFERENCE = 'SELECT_LANGUAGE_PREFERENCE';